# Generated by Django 6.0.5 on 2026-05-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
